"""add next_step_due to applications

Revision ID: 08a103bddcd6
Revises: e6d5835d693e
Create Date: 2026-09-28 10:15:09.057853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a103bddcd6'
down_revision: Union[str, Sequence[str], None] = 'e6d5835d693e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('next_step_due', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'next_step_due')
    # ### end Alembic commands ###
