"""record what reading a discovered posting found

Revision ID: 192987c82f73
Revises: fa5be666dc21
Create Date: 2026-09-10 16:00:11.974373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192987c82f73'
down_revision: Union[str, Sequence[str], None] = 'fa5be666dc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_jobs', sa.Column('jd_text', sa.Text(), nullable=True))
    op.add_column('discovered_jobs', sa.Column('jd_parsed', sa.JSON(), nullable=True))
    op.add_column('discovered_jobs', sa.Column('eligibility', sa.JSON(), nullable=True))
    op.add_column('discovered_jobs', sa.Column('enriched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovered_jobs', 'enriched_at')
    op.drop_column('discovered_jobs', 'eligibility')
    op.drop_column('discovered_jobs', 'jd_parsed')
    op.drop_column('discovered_jobs', 'jd_text')
    # ### end Alembic commands ###
