"""add target companies for direct board polling

Revision ID: 439de67f42b9
Revises: a36bdc2ccbd3
Create Date: 2026-09-10 18:47:42.446562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439de67f42b9'
down_revision: Union[str, Sequence[str], None] = 'a36bdc2ccbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ats', sa.String(length=32), nullable=False),
    sa.Column('board', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ats', 'host', 'board', 'site', name='uq_target_board')
    )
    op.add_column('discovered_jobs', sa.Column('target_company_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_discovered_jobs_target_company', 'discovered_jobs', 'target_companies', ['target_company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_discovered_jobs_target_company', 'discovered_jobs', type_='foreignkey')
    op.drop_column('discovered_jobs', 'target_company_id')
    op.drop_table('target_companies')
    # ### end Alembic commands ###
