"""create applications table

Revision ID: 5a510583d8ee
Revises: 
Create Date: 2026-07-10 22:06:06.700203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a510583d8ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('internship', 'scholarship', name='applicationtype'), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'drafting', 'ready', 'applied', 'recruiter_engaged', 'phone_screen', 'technical_interview', 'onsite', 'offer', 'accepted', 'declined', 'rejected', 'ghosted', 'missed_deadline', name='applicationstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority'), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role_or_program', sa.String(length=255), nullable=False),
    sa.Column('posting_url', sa.String(length=2048), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('jd_parsed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
