"""add discovered_jobs staging table

Revision ID: fa5be666dc21
Revises: f47832e5e6dc
Create Date: 2026-09-10 15:52:32.872171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5be666dc21'
down_revision: Union[str, Sequence[str], None] = 'f47832e5e6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role_or_program', sa.String(length=255), nullable=False),
    sa.Column('posting_url', sa.String(length=2048), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('role_family', sa.String(length=64), nullable=True),
    sa.Column('possible_application_ids', sa.JSON(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'accepted', 'dismissed', 'filtered', name='discoverystate'), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_discovered_source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('discovered_jobs')
    # Dropping the table does NOT drop the enum type it created — autogenerate
    # leaves that behind, and a later re-upgrade then fails with "type
    # discoverystate already exists". Gated on the dialect because SQLite has no
    # enum types at all (it renders them as VARCHAR plus a CHECK), matching how
    # the rest of this chain handles dialect differences.
    if op.get_bind().dialect.name == "postgresql":
        sa.Enum(name="discoverystate").drop(op.get_bind(), checkfirst=True)
