"""add role_family to applications

Revision ID: fa83dd1ecb8a
Revises: 1f38a3b23bae
Create Date: 2026-09-01 16:26:51.650921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa83dd1ecb8a'
down_revision: Union[str, Sequence[str], None] = '1f38a3b23bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('role_family', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'role_family')
    # ### end Alembic commands ###
